/*
 * Generated by JasperReports - 2/9/10 11:16 AM
 */
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.engine.fill.*;

import java.util.*;
import java.math.*;
import java.text.*;
import java.io.*;
import java.net.*;

import net.sf.jasperreports.engine.*;
import java.util.*;
import net.sf.jasperreports.engine.data.*;


/**
 *
 */
public class rptLedgerDayWise_LedAbstract_1265694414375_364963 extends JREvaluator
{


    /**
     *
     */
    private JRFillParameter parameter_REPORT_LOCALE = null;
    private JRFillParameter parameter_REPORT_TIME_ZONE = null;
    private JRFillParameter parameter_REPORT_VIRTUALIZER = null;
    private JRFillParameter parameter_MCUSTOMER = null;
    private JRFillParameter parameter_TDT = null;
    private JRFillParameter parameter_REPORT_SCRIPTLET = null;
    private JRFillParameter parameter_REPORT_PARAMETERS_MAP = null;
    private JRFillParameter parameter_REPORT_CONNECTION = null;
    private JRFillParameter parameter_FDT = null;
    private JRFillParameter parameter_REPORT_CLASS_LOADER = null;
    private JRFillParameter parameter_REPORT_DATA_SOURCE = null;
    private JRFillParameter parameter_REPORT_URL_HANDLER_FACTORY = null;
    private JRFillParameter parameter_IS_IGNORE_PAGINATION = null;
    private JRFillParameter parameter_REPORT_MAX_COUNT = null;
    private JRFillParameter parameter_TODT = null;
    private JRFillParameter parameter_FROMDT = null;
    private JRFillParameter parameter_REPORT_DATE_FORMAT_FACTORY = null;
    private JRFillParameter parameter_REPORT_RESOURCE_BUNDLE = null;
    private JRFillField field_product = null;
    private JRFillField field_id = null;
    private JRFillField field_ratetype = null;
    private JRFillField field_subsidy = null;
    private JRFillField field_rate = null;
    private JRFillField field_prodtype = null;
    private JRFillField field_netqty = null;
    private JRFillField field_commiamt = null;
    private JRFillField field_prodname = null;
    private JRFillField field_rtname = null;
    private JRFillField field_custname = null;
    private JRFillVariable variable_PAGE_NUMBER = null;
    private JRFillVariable variable_COLUMN_NUMBER = null;
    private JRFillVariable variable_REPORT_COUNT = null;
    private JRFillVariable variable_PAGE_COUNT = null;
    private JRFillVariable variable_COLUMN_COUNT = null;
    private JRFillVariable variable_product_COUNT = null;
    private JRFillVariable variable_qty = null;
    private JRFillVariable variable_MilkTotal = null;
    private JRFillVariable variable_cmiAmt = null;
    private JRFillVariable variable_grCommiAmt = null;
    private JRFillVariable variable_amount = null;
    private JRFillVariable variable_subsidyamt = null;
    private JRFillVariable variable_NetAmt = null;
    private JRFillVariable variable_TotalNetAmt = null;
    private JRFillVariable variable_grAmount = null;
    private JRFillVariable variable_grSubsidy = null;


    /**
     *
     */
    public void customizedInit(
        Map pm,
        Map fm,
        Map vm
        )
    {
        initParams(pm);
        initFields(fm);
        initVars(vm);
    }


    /**
     *
     */
    private void initParams(Map pm)
    {
        parameter_REPORT_LOCALE = (JRFillParameter)pm.get("REPORT_LOCALE");
        parameter_REPORT_TIME_ZONE = (JRFillParameter)pm.get("REPORT_TIME_ZONE");
        parameter_REPORT_VIRTUALIZER = (JRFillParameter)pm.get("REPORT_VIRTUALIZER");
        parameter_MCUSTOMER = (JRFillParameter)pm.get("MCUSTOMER");
        parameter_TDT = (JRFillParameter)pm.get("TDT");
        parameter_REPORT_SCRIPTLET = (JRFillParameter)pm.get("REPORT_SCRIPTLET");
        parameter_REPORT_PARAMETERS_MAP = (JRFillParameter)pm.get("REPORT_PARAMETERS_MAP");
        parameter_REPORT_CONNECTION = (JRFillParameter)pm.get("REPORT_CONNECTION");
        parameter_FDT = (JRFillParameter)pm.get("FDT");
        parameter_REPORT_CLASS_LOADER = (JRFillParameter)pm.get("REPORT_CLASS_LOADER");
        parameter_REPORT_DATA_SOURCE = (JRFillParameter)pm.get("REPORT_DATA_SOURCE");
        parameter_REPORT_URL_HANDLER_FACTORY = (JRFillParameter)pm.get("REPORT_URL_HANDLER_FACTORY");
        parameter_IS_IGNORE_PAGINATION = (JRFillParameter)pm.get("IS_IGNORE_PAGINATION");
        parameter_REPORT_MAX_COUNT = (JRFillParameter)pm.get("REPORT_MAX_COUNT");
        parameter_TODT = (JRFillParameter)pm.get("TODT");
        parameter_FROMDT = (JRFillParameter)pm.get("FROMDT");
        parameter_REPORT_DATE_FORMAT_FACTORY = (JRFillParameter)pm.get("REPORT_DATE_FORMAT_FACTORY");
        parameter_REPORT_RESOURCE_BUNDLE = (JRFillParameter)pm.get("REPORT_RESOURCE_BUNDLE");
    }


    /**
     *
     */
    private void initFields(Map fm)
    {
        field_product = (JRFillField)fm.get("product");
        field_id = (JRFillField)fm.get("id");
        field_ratetype = (JRFillField)fm.get("ratetype");
        field_subsidy = (JRFillField)fm.get("subsidy");
        field_rate = (JRFillField)fm.get("rate");
        field_prodtype = (JRFillField)fm.get("prodtype");
        field_netqty = (JRFillField)fm.get("netqty");
        field_commiamt = (JRFillField)fm.get("commiamt");
        field_prodname = (JRFillField)fm.get("prodname");
        field_rtname = (JRFillField)fm.get("rtname");
        field_custname = (JRFillField)fm.get("custname");
    }


    /**
     *
     */
    private void initVars(Map vm)
    {
        variable_PAGE_NUMBER = (JRFillVariable)vm.get("PAGE_NUMBER");
        variable_COLUMN_NUMBER = (JRFillVariable)vm.get("COLUMN_NUMBER");
        variable_REPORT_COUNT = (JRFillVariable)vm.get("REPORT_COUNT");
        variable_PAGE_COUNT = (JRFillVariable)vm.get("PAGE_COUNT");
        variable_COLUMN_COUNT = (JRFillVariable)vm.get("COLUMN_COUNT");
        variable_product_COUNT = (JRFillVariable)vm.get("product_COUNT");
        variable_qty = (JRFillVariable)vm.get("qty");
        variable_MilkTotal = (JRFillVariable)vm.get("MilkTotal");
        variable_cmiAmt = (JRFillVariable)vm.get("cmiAmt");
        variable_grCommiAmt = (JRFillVariable)vm.get("grCommiAmt");
        variable_amount = (JRFillVariable)vm.get("amount");
        variable_subsidyamt = (JRFillVariable)vm.get("subsidyamt");
        variable_NetAmt = (JRFillVariable)vm.get("NetAmt");
        variable_TotalNetAmt = (JRFillVariable)vm.get("TotalNetAmt");
        variable_grAmount = (JRFillVariable)vm.get("grAmount");
        variable_grSubsidy = (JRFillVariable)vm.get("grSubsidy");
    }


    /**
     *
     */
    public Object evaluate(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 0 : 
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 1 : 
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 2 : 
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 3 : 
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 4 : 
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 5 : 
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 6 : 
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 7 : 
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 8 : 
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 9 : 
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 10 : 
            {
                value = (java.lang.Double)(new Double(((java.math.BigDecimal)field_netqty.getValue()).doubleValue()));
                break;
            }
            case 11 : 
            {
                value = (java.lang.Double)(new Double(( ((java.lang.Integer)field_prodtype.getValue()).intValue() == 1 ? ((java.math.BigDecimal)field_netqty.getValue()).doubleValue() : 0.00)));
                break;
            }
            case 12 : 
            {
                value = (java.lang.Double)(new Double(((java.math.BigDecimal)field_commiamt.getValue()).doubleValue()));
                break;
            }
            case 13 : 
            {
                value = (java.lang.Double)(new Double(((java.math.BigDecimal)field_commiamt.getValue()).doubleValue()));
                break;
            }
            case 14 : 
            {
                value = (java.lang.Double)(new Double(((java.lang.Double)variable_qty.getValue()).doubleValue() * ((java.math.BigDecimal)field_rate.getValue()).doubleValue()));
                break;
            }
            case 15 : 
            {
                value = (java.lang.Double)(new Double(((java.math.BigDecimal)field_subsidy.getValue()).doubleValue()));
                break;
            }
            case 16 : 
            {
                value = (java.lang.Double)(((java.lang.Integer)field_ratetype.getValue()).intValue() == 2 ? new Double(((java.lang.Double)variable_amount.getValue()).doubleValue() - 
(((java.lang.Double)variable_cmiAmt.getValue()).doubleValue() + ((java.lang.Double)variable_subsidyamt.getValue()).doubleValue())) :
new Double(((java.lang.Double)variable_amount.getValue()).doubleValue() - ((java.lang.Double)variable_subsidyamt.getValue()).doubleValue()));
                break;
            }
            case 17 : 
            {
                value = (java.lang.Double)(new Double((((java.math.BigDecimal)field_netqty.getValue()).doubleValue() * ((java.math.BigDecimal)field_rate.getValue()).doubleValue()) - 
(((java.math.BigDecimal)field_commiamt.getValue()).doubleValue() +((java.math.BigDecimal)field_subsidy.getValue()).doubleValue() )));
                break;
            }
            case 18 : 
            {
                value = (java.lang.Double)(new Double(((java.math.BigDecimal)field_netqty.getValue()).doubleValue() * ((java.math.BigDecimal)field_rate.getValue()).doubleValue()));
                break;
            }
            case 19 : 
            {
                value = (java.lang.Double)(new Double(((java.math.BigDecimal)field_subsidy.getValue()).doubleValue()));
                break;
            }
            case 20 : 
            {
                value = (java.lang.Object)(((java.lang.Long)field_product.getValue()));
                break;
            }
            case 21 : 
            {
                value = (java.lang.String)(((java.lang.String)field_prodname.getValue()));
                break;
            }
            case 22 : 
            {
                value = (java.lang.Double)(((java.lang.Double)variable_qty.getValue()));
                break;
            }
            case 23 : 
            {
                value = (java.lang.Double)(((java.lang.Double)variable_cmiAmt.getValue()));
                break;
            }
            case 24 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_rate.getValue()));
                break;
            }
            case 25 : 
            {
                value = (java.lang.Double)(((java.lang.Double)variable_amount.getValue()));
                break;
            }
            case 26 : 
            {
                value = (java.lang.Double)(((java.lang.Double)variable_subsidyamt.getValue()));
                break;
            }
            case 27 : 
            {
                value = (java.lang.Double)(((java.lang.Double)variable_NetAmt.getValue()));
                break;
            }
            case 28 : 
            {
                value = (java.lang.String)(((java.lang.String)field_custname.getValue()));
                break;
            }
            case 29 : 
            {
                value = (java.lang.String)(((java.lang.String)field_rtname.getValue()));
                break;
            }
            case 30 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_FDT.getValue()));
                break;
            }
            case 31 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_TDT.getValue()));
                break;
            }
            case 32 : 
            {
                value = (java.lang.Double)(((java.lang.Double)variable_MilkTotal.getValue()));
                break;
            }
            case 33 : 
            {
                value = (java.lang.Double)(((java.lang.Double)variable_grCommiAmt.getValue()));
                break;
            }
            case 34 : 
            {
                value = (java.lang.Double)(((java.lang.Double)variable_TotalNetAmt.getValue()));
                break;
            }
            case 35 : 
            {
                value = (java.lang.Double)(((java.lang.Double)variable_grAmount.getValue()));
                break;
            }
            case 36 : 
            {
                value = (java.lang.Double)(((java.lang.Double)variable_grSubsidy.getValue()));
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


    /**
     *
     */
    public Object evaluateOld(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 0 : 
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 1 : 
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 2 : 
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 3 : 
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 4 : 
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 5 : 
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 6 : 
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 7 : 
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 8 : 
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 9 : 
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 10 : 
            {
                value = (java.lang.Double)(new Double(((java.math.BigDecimal)field_netqty.getOldValue()).doubleValue()));
                break;
            }
            case 11 : 
            {
                value = (java.lang.Double)(new Double(( ((java.lang.Integer)field_prodtype.getOldValue()).intValue() == 1 ? ((java.math.BigDecimal)field_netqty.getOldValue()).doubleValue() : 0.00)));
                break;
            }
            case 12 : 
            {
                value = (java.lang.Double)(new Double(((java.math.BigDecimal)field_commiamt.getOldValue()).doubleValue()));
                break;
            }
            case 13 : 
            {
                value = (java.lang.Double)(new Double(((java.math.BigDecimal)field_commiamt.getOldValue()).doubleValue()));
                break;
            }
            case 14 : 
            {
                value = (java.lang.Double)(new Double(((java.lang.Double)variable_qty.getOldValue()).doubleValue() * ((java.math.BigDecimal)field_rate.getOldValue()).doubleValue()));
                break;
            }
            case 15 : 
            {
                value = (java.lang.Double)(new Double(((java.math.BigDecimal)field_subsidy.getOldValue()).doubleValue()));
                break;
            }
            case 16 : 
            {
                value = (java.lang.Double)(((java.lang.Integer)field_ratetype.getOldValue()).intValue() == 2 ? new Double(((java.lang.Double)variable_amount.getOldValue()).doubleValue() - 
(((java.lang.Double)variable_cmiAmt.getOldValue()).doubleValue() + ((java.lang.Double)variable_subsidyamt.getOldValue()).doubleValue())) :
new Double(((java.lang.Double)variable_amount.getOldValue()).doubleValue() - ((java.lang.Double)variable_subsidyamt.getOldValue()).doubleValue()));
                break;
            }
            case 17 : 
            {
                value = (java.lang.Double)(new Double((((java.math.BigDecimal)field_netqty.getOldValue()).doubleValue() * ((java.math.BigDecimal)field_rate.getOldValue()).doubleValue()) - 
(((java.math.BigDecimal)field_commiamt.getOldValue()).doubleValue() +((java.math.BigDecimal)field_subsidy.getOldValue()).doubleValue() )));
                break;
            }
            case 18 : 
            {
                value = (java.lang.Double)(new Double(((java.math.BigDecimal)field_netqty.getOldValue()).doubleValue() * ((java.math.BigDecimal)field_rate.getOldValue()).doubleValue()));
                break;
            }
            case 19 : 
            {
                value = (java.lang.Double)(new Double(((java.math.BigDecimal)field_subsidy.getOldValue()).doubleValue()));
                break;
            }
            case 20 : 
            {
                value = (java.lang.Object)(((java.lang.Long)field_product.getOldValue()));
                break;
            }
            case 21 : 
            {
                value = (java.lang.String)(((java.lang.String)field_prodname.getOldValue()));
                break;
            }
            case 22 : 
            {
                value = (java.lang.Double)(((java.lang.Double)variable_qty.getOldValue()));
                break;
            }
            case 23 : 
            {
                value = (java.lang.Double)(((java.lang.Double)variable_cmiAmt.getOldValue()));
                break;
            }
            case 24 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_rate.getOldValue()));
                break;
            }
            case 25 : 
            {
                value = (java.lang.Double)(((java.lang.Double)variable_amount.getOldValue()));
                break;
            }
            case 26 : 
            {
                value = (java.lang.Double)(((java.lang.Double)variable_subsidyamt.getOldValue()));
                break;
            }
            case 27 : 
            {
                value = (java.lang.Double)(((java.lang.Double)variable_NetAmt.getOldValue()));
                break;
            }
            case 28 : 
            {
                value = (java.lang.String)(((java.lang.String)field_custname.getOldValue()));
                break;
            }
            case 29 : 
            {
                value = (java.lang.String)(((java.lang.String)field_rtname.getOldValue()));
                break;
            }
            case 30 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_FDT.getValue()));
                break;
            }
            case 31 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_TDT.getValue()));
                break;
            }
            case 32 : 
            {
                value = (java.lang.Double)(((java.lang.Double)variable_MilkTotal.getOldValue()));
                break;
            }
            case 33 : 
            {
                value = (java.lang.Double)(((java.lang.Double)variable_grCommiAmt.getOldValue()));
                break;
            }
            case 34 : 
            {
                value = (java.lang.Double)(((java.lang.Double)variable_TotalNetAmt.getOldValue()));
                break;
            }
            case 35 : 
            {
                value = (java.lang.Double)(((java.lang.Double)variable_grAmount.getOldValue()));
                break;
            }
            case 36 : 
            {
                value = (java.lang.Double)(((java.lang.Double)variable_grSubsidy.getOldValue()));
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


    /**
     *
     */
    public Object evaluateEstimated(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 0 : 
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 1 : 
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 2 : 
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 3 : 
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 4 : 
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 5 : 
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 6 : 
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 7 : 
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 8 : 
            {
                value = (java.lang.Integer)(new Integer(1));
                break;
            }
            case 9 : 
            {
                value = (java.lang.Integer)(new Integer(0));
                break;
            }
            case 10 : 
            {
                value = (java.lang.Double)(new Double(((java.math.BigDecimal)field_netqty.getValue()).doubleValue()));
                break;
            }
            case 11 : 
            {
                value = (java.lang.Double)(new Double(( ((java.lang.Integer)field_prodtype.getValue()).intValue() == 1 ? ((java.math.BigDecimal)field_netqty.getValue()).doubleValue() : 0.00)));
                break;
            }
            case 12 : 
            {
                value = (java.lang.Double)(new Double(((java.math.BigDecimal)field_commiamt.getValue()).doubleValue()));
                break;
            }
            case 13 : 
            {
                value = (java.lang.Double)(new Double(((java.math.BigDecimal)field_commiamt.getValue()).doubleValue()));
                break;
            }
            case 14 : 
            {
                value = (java.lang.Double)(new Double(((java.lang.Double)variable_qty.getEstimatedValue()).doubleValue() * ((java.math.BigDecimal)field_rate.getValue()).doubleValue()));
                break;
            }
            case 15 : 
            {
                value = (java.lang.Double)(new Double(((java.math.BigDecimal)field_subsidy.getValue()).doubleValue()));
                break;
            }
            case 16 : 
            {
                value = (java.lang.Double)(((java.lang.Integer)field_ratetype.getValue()).intValue() == 2 ? new Double(((java.lang.Double)variable_amount.getEstimatedValue()).doubleValue() - 
(((java.lang.Double)variable_cmiAmt.getEstimatedValue()).doubleValue() + ((java.lang.Double)variable_subsidyamt.getEstimatedValue()).doubleValue())) :
new Double(((java.lang.Double)variable_amount.getEstimatedValue()).doubleValue() - ((java.lang.Double)variable_subsidyamt.getEstimatedValue()).doubleValue()));
                break;
            }
            case 17 : 
            {
                value = (java.lang.Double)(new Double((((java.math.BigDecimal)field_netqty.getValue()).doubleValue() * ((java.math.BigDecimal)field_rate.getValue()).doubleValue()) - 
(((java.math.BigDecimal)field_commiamt.getValue()).doubleValue() +((java.math.BigDecimal)field_subsidy.getValue()).doubleValue() )));
                break;
            }
            case 18 : 
            {
                value = (java.lang.Double)(new Double(((java.math.BigDecimal)field_netqty.getValue()).doubleValue() * ((java.math.BigDecimal)field_rate.getValue()).doubleValue()));
                break;
            }
            case 19 : 
            {
                value = (java.lang.Double)(new Double(((java.math.BigDecimal)field_subsidy.getValue()).doubleValue()));
                break;
            }
            case 20 : 
            {
                value = (java.lang.Object)(((java.lang.Long)field_product.getValue()));
                break;
            }
            case 21 : 
            {
                value = (java.lang.String)(((java.lang.String)field_prodname.getValue()));
                break;
            }
            case 22 : 
            {
                value = (java.lang.Double)(((java.lang.Double)variable_qty.getEstimatedValue()));
                break;
            }
            case 23 : 
            {
                value = (java.lang.Double)(((java.lang.Double)variable_cmiAmt.getEstimatedValue()));
                break;
            }
            case 24 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_rate.getValue()));
                break;
            }
            case 25 : 
            {
                value = (java.lang.Double)(((java.lang.Double)variable_amount.getEstimatedValue()));
                break;
            }
            case 26 : 
            {
                value = (java.lang.Double)(((java.lang.Double)variable_subsidyamt.getEstimatedValue()));
                break;
            }
            case 27 : 
            {
                value = (java.lang.Double)(((java.lang.Double)variable_NetAmt.getEstimatedValue()));
                break;
            }
            case 28 : 
            {
                value = (java.lang.String)(((java.lang.String)field_custname.getValue()));
                break;
            }
            case 29 : 
            {
                value = (java.lang.String)(((java.lang.String)field_rtname.getValue()));
                break;
            }
            case 30 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_FDT.getValue()));
                break;
            }
            case 31 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_TDT.getValue()));
                break;
            }
            case 32 : 
            {
                value = (java.lang.Double)(((java.lang.Double)variable_MilkTotal.getEstimatedValue()));
                break;
            }
            case 33 : 
            {
                value = (java.lang.Double)(((java.lang.Double)variable_grCommiAmt.getEstimatedValue()));
                break;
            }
            case 34 : 
            {
                value = (java.lang.Double)(((java.lang.Double)variable_TotalNetAmt.getEstimatedValue()));
                break;
            }
            case 35 : 
            {
                value = (java.lang.Double)(((java.lang.Double)variable_grAmount.getEstimatedValue()));
                break;
            }
            case 36 : 
            {
                value = (java.lang.Double)(((java.lang.Double)variable_grSubsidy.getEstimatedValue()));
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


}
